const {chromium} = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
(async () => {
  const browser = await chromium.launch({channel:'chrome', headless:true});
  const page = await browser.newPage({viewport:{width:1440,height:1000}});
  const errors = [];
  let evaluations = 0;
  page.on('pageerror', error => errors.push(error.message));
  page.on('request', request => { if (request.url().endsWith('/api/evaluate')) evaluations++; });
  await page.goto('http://127.0.0.1:8777');
  await page.locator('.example').first().waitFor();
  assert.equal(await page.locator('.room').count(), 3);
  await page.locator('#evaluate').click();
  await page.locator('#result').waitFor({state:'visible'});
  assert.match(await page.locator('#result-source').innerText(), /fixture/i);
  assert.equal(await page.locator('#lights').inputValue(), '2');
  assert.equal(await page.locator('#apply').isEnabled(), true);
  const beforeThreshold = evaluations;
  await page.locator('#threshold').fill('1');
  assert.equal(await page.locator('#apply').isDisabled(), true);
  await page.locator('#threshold').fill('0.7');
  assert.equal(await page.locator('#apply').isEnabled(), true);
  assert.equal(evaluations, beforeThreshold, 'Threshold must reuse answers');
  await page.locator('.inspector summary').click();
  const request = JSON.parse(await page.locator('#raw-request').innerText());
  assert.deepEqual(Object.keys(request.questions), ['action','brightness','applicable']);
  assert.equal(request.state.selected_room, 'living');
  await page.locator('.inspector summary').click();
  await page.locator('#apply').click();
  assert.equal(await page.locator('#lights').inputValue(), '1');
  assert.equal(await page.locator('#apply').isDisabled(), true);
  await page.locator('#reset').click();
  assert.equal(await page.locator('#result').isHidden(), true);
  await page.getByRole('button', {name:'Open the blinds.', exact:true}).click();
  await page.locator('#evaluate').click();
  await page.locator('#result').waitFor({state:'visible'});
  assert.match(await page.locator('#score-detail').innerText(), /unused/i);
  await page.locator('#apply').click();
  assert.equal(await page.locator('#blinds').innerText(), 'Open');
  await page.getByRole('button', {name:'Put some music on.', exact:true}).click();
  await page.locator('#evaluate').click();
  await page.locator('#result').waitFor({state:'visible'});
  await page.locator('#apply').click();
  assert.equal(await page.locator('#music').innerText(), 'On');
  await page.getByRole('button', {name:'What is the weather tomorrow?', exact:true}).click();
  await page.locator('#evaluate').click();
  await page.locator('#result').waitFor({state:'visible'});
  assert.equal(await page.locator('#apply').isDisabled(), true);
  await page.locator('#request-text').fill('An edited request with no fixture.');
  assert.equal(await page.locator('#result').isHidden(), true);
  await page.locator('#evaluate').click();
  await page.waitForFunction(() => document.querySelector('#status').textContent.includes('exact fixture'));
  await page.locator('#mode').selectOption('live');
  await page.locator('#evaluate').click();
  await page.waitForFunction(() => document.querySelector('#status').textContent.includes('Set TYPESAFE_API_KEY'));
  assert.equal(await page.locator('#result').isHidden(), true);
  await page.locator('#mode').selectOption('fixture');
  await page.locator('.example').first().click();
  await page.locator('#reset').click();
  let release;
  const gate = new Promise(resolve => { release = resolve; });
  let received;
  const started = new Promise(resolve => { received = resolve; });
  await page.route('**/api/evaluate', async route => {
    const response = await route.fetch();
    received();
    await gate;
    await route.fulfill({response});
  });
  await page.locator('#evaluate').click();
  await started;
  await page.locator('#request-text').fill('New request while response is in flight.');
  release();
  await page.waitForFunction(() => !document.querySelector('#evaluate').disabled);
  assert.equal(await page.locator('#result').isHidden(), true, 'Late answer must stay stale');
  assert.equal(await page.locator('#lights').inputValue(), '2');
  await page.unroute('**/api/evaluate');
  await page.locator('.example').first().click();
  await page.locator('#evaluate').click();
  await page.locator('#result').waitFor({state:'visible'});
  fs.mkdirSync('demos/jev_habitat/screenshots',{recursive:true});
  for (const [name,width,height] of [['desktop',1440,1000],['mobile',390,844]]) {
    await page.setViewportSize({width,height});
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `${name} overflow`);
    await page.emulateMedia({reducedMotion:'reduce'});
    await page.evaluate(() => window.scrollTo({top:0,behavior:'instant'}));
    await page.screenshot({animations:'disabled',path:`demos/jev_habitat/screenshots/${name}.png`,fullPage:true});
  }
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.locator('#apply').click();
  assert.equal(await page.locator('#lights').inputValue(), '1');
  assert.deepEqual(errors, []);
  console.log('PASS: room selection; lights/music/blinds apply; local threshold with no request; inspector; no-change; edited-fixture rejection; missing-key error; stale response discard; desktop/mobile layout; reduced motion; zero page errors.');
  await browser.close();
})().catch(error => {console.error(error); process.exit(1);});
